# Generated by Django 4.0 on 2022-01-14 17:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaSubida', models.DateField()),
                ('Autor', models.CharField(max_length=30)),
                ('Titulo', models.CharField(max_length=20)),
                ('Subtitulo', models.CharField(max_length=40)),
                ('Cuerpo', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
