# Generated by Django 4.0 on 2022-01-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='FechaSubida',
            new_name='Fecha',
        ),
    ]
