# Generated by Django 4.0 on 2022-02-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0005_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Foto',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
