# Generated by Django 4.0 on 2022-02-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0007_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
