# Generated by Django 4.0 on 2022-02-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0008_delete_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Equipo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
