# Generated by Django 4.0 on 2022-02-10 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('AppHome', '0009_post_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Subtitulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='Titulo',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Asunto', models.CharField(max_length=60)),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
